### ISSUE TITLE
Create concept for trip execution

### ISSUE THREAD

**Issue by joshuaschu** [raphaelmue/travlyn#48]

**Comment by raphaelmue** [comment]
1. Start Trip button in Trip Information Page
2. Send current location to server: Server reorders stops (TSP with distance matrix of airlines) and calculate navigation to origin after last stop passed if user allows
3. Show complete trip route with current location
4. When clicking start, navigation to first stop starts
5. When arriving at stop, popup opens and shows stop details with possibility of entering a rating, price and time effort
6. When clicking continue button, navigation to next stop starts
7. When trip finished, possibility to add trip rating

APIs:
- `GET` `/trip/{tripId}/execution?latitude&longitude&reorderAllowed&roundTrip`: Route containing waypoints and instructions
- `GET` `/trip/{tripId}/route?latitude&longitude&targetStopId`: Route containing waypoints and instructions
- `POST` `/stop/{stopId}/pricing?pricing`: updated Stop
- `POST` `/stop/{stopId}/timeEffort?timeEffort`: updated Stop
- `PUT` `/trip/{tripId}/rating?rating`: updated Trip

Frontend:
- Show complete Route on map (API 1)
- Navigation between stops with **skip** button (API 1)
- Request rerouting when user leaves route (API 2)
- Show dialog with stop information with **continue** button and with updating pricing, timeEffort and rating (API 3, 4)
- Show dialog after trip has finished (API 5)
- Optional: Notification when executing trip or hint when exiting navigation
